name: Node.js CD

on:
  push:
    branches: [master]

jobs:
  deploy_app:
    # needs: inspect_pull_request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: 'cube-level-midnight-v2'
          heroku_email: '${{secrets.HEROKU_EMAIL}}'
